-- =====================================================================
-- SEA RETAIL BANKING DEMO - FOUNDATION SETUP
-- Purpose: Create database structure for Malaysia/Singapore banks
-- Run as: ACCOUNTADMIN
-- =====================================================================

USE ROLE ACCOUNTADMIN;

-- =====================================================================
-- 1. CREATE DATABASE AND SCHEMAS
-- =====================================================================

CREATE OR REPLACE DATABASE RETAIL_BANKING_DEMO
    COMMENT = 'SEA Retail Banking Demo - Malaysia/Singapore';

CREATE SCHEMA IF NOT EXISTS RETAIL_BANKING_DEMO.BRONZE 
    COMMENT = 'Raw landing zone for source data';
    
CREATE SCHEMA IF NOT EXISTS RETAIL_BANKING_DEMO.SILVER 
    COMMENT = 'Cleansed and validated data';
    
CREATE SCHEMA IF NOT EXISTS RETAIL_BANKING_DEMO.GOLD 
    COMMENT = 'Business-ready curated data';

CREATE SCHEMA IF NOT EXISTS RETAIL_BANKING_DEMO.DOCS 
    COMMENT = 'Banking documents and policies for Cortex Search';

CREATE SCHEMA IF NOT EXISTS RETAIL_BANKING_DEMO.ANALYTICS
    COMMENT = 'Business analytics and KPI views';

-- =====================================================================
-- 2. CREATE WAREHOUSE
-- =====================================================================

CREATE WAREHOUSE IF NOT EXISTS BANKING_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for SEA banking demo';

-- =====================================================================
-- 3. CREATE ROLE AND GRANT PERMISSIONS
-- =====================================================================

CREATE ROLE IF NOT EXISTS BANKING_APP_ROLE
    COMMENT = 'Role for Streamlit app and end users';

-- Database & schema usage
GRANT USAGE ON DATABASE RETAIL_BANKING_DEMO TO ROLE BANKING_APP_ROLE;

GRANT USAGE ON SCHEMA RETAIL_BANKING_DEMO.BRONZE    TO ROLE BANKING_APP_ROLE;
GRANT USAGE ON SCHEMA RETAIL_BANKING_DEMO.SILVER    TO ROLE BANKING_APP_ROLE;
GRANT USAGE ON SCHEMA RETAIL_BANKING_DEMO.GOLD      TO ROLE BANKING_APP_ROLE;
GRANT USAGE ON SCHEMA RETAIL_BANKING_DEMO.DOCS      TO ROLE BANKING_APP_ROLE;
GRANT USAGE ON SCHEMA RETAIL_BANKING_DEMO.ANALYTICS TO ROLE BANKING_APP_ROLE;

-- Table access (current)
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_BANKING_DEMO.BRONZE    TO ROLE BANKING_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_BANKING_DEMO.SILVER    TO ROLE BANKING_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_BANKING_DEMO.GOLD      TO ROLE BANKING_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_BANKING_DEMO.ANALYTICS TO ROLE BANKING_APP_ROLE;

-- Table access (future)
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_BANKING_DEMO.BRONZE    TO ROLE BANKING_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_BANKING_DEMO.SILVER    TO ROLE BANKING_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_BANKING_DEMO.GOLD      TO ROLE BANKING_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_BANKING_DEMO.ANALYTICS TO ROLE BANKING_APP_ROLE;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE BANKING_WH TO ROLE BANKING_APP_ROLE;

-- Cortex privileges
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER         TO ROLE BANKING_APP_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_ANALYST_USER TO ROLE BANKING_APP_ROLE;

-- Streamlit creation privilege
GRANT CREATE STREAMLIT ON SCHEMA RETAIL_BANKING_DEMO.SILVER TO ROLE ACCOUNTADMIN;
GRANT CREATE STREAMLIT ON SCHEMA RETAIL_BANKING_DEMO.SILVER TO ROLE BANKING_APP_ROLE;

-- =====================================================================
-- 4. CREATE STAGES FOR FILES
-- =====================================================================

USE DATABASE RETAIL_BANKING_DEMO;
USE SCHEMA SILVER;

CREATE STAGE IF NOT EXISTS SEMANTIC_STAGE
    COMMENT = 'Stage for Cortex Analyst YAML files';

CREATE STAGE IF NOT EXISTS APP_STAGE
    COMMENT = 'Stage for Streamlit app code and assets';

CREATE STAGE IF NOT EXISTS DOCS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for banking policy documents';

-- Stage access
GRANT READ ON STAGE RETAIL_BANKING_DEMO.SILVER.SEMANTIC_STAGE TO ROLE BANKING_APP_ROLE;
GRANT READ ON STAGE RETAIL_BANKING_DEMO.SILVER.APP_STAGE      TO ROLE BANKING_APP_ROLE;
GRANT READ, WRITE ON STAGE RETAIL_BANKING_DEMO.SILVER.DOCS_STAGE TO ROLE BANKING_APP_ROLE;

-- =====================================================================
-- 5. ENABLE CORTEX FEATURES
-- =====================================================================

ALTER ACCOUNT SET ENABLE_CORTEX_ANALYST = TRUE;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- =====================================================================
-- 6. CREATE EMAIL NOTIFICATION INTEGRATION (USED BY APP)
-- =====================================================================

CREATE NOTIFICATION INTEGRATION IF NOT EXISTS EMAIL_INT
    TYPE    = EMAIL
    ENABLED = TRUE
    COMMENT = 'Email integration for sending banking reports';

GRANT USAGE ON INTEGRATION EMAIL_INT TO ROLE BANKING_APP_ROLE;

-- =====================================================================
-- 7. VERIFICATION
-- =====================================================================

SHOW DATABASES LIKE 'RETAIL_BANKING_DEMO';
SHOW SCHEMAS IN DATABASE RETAIL_BANKING_DEMO;
SHOW WAREHOUSES LIKE 'BANKING_WH';
SHOW ROLES LIKE 'BANKING_APP_ROLE';
SHOW STAGES IN SCHEMA RETAIL_BANKING_DEMO.SILVER;

SHOW PARAMETERS LIKE 'ENABLE_CORTEX%' IN ACCOUNT;
SELECT CURRENT_REGION() AS MY_REGION;

SELECT '✓ FOUNDATION SETUP COMPLETE!' AS STATUS;
