-- =====================================================================
-- SEA RETAIL BANKING DEMO - DATA QUALITY VALIDATION
-- Purpose: Create SILVER layer with data quality checks
-- Run as: ACCOUNTADMIN
-- =====================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_BANKING_DEMO;
USE WAREHOUSE BANKING_WH;

-- =====================================================================
-- SILVER LAYER - STAGING AND QUALITY CHECKS
-- =====================================================================

USE SCHEMA SILVER;

-- ---------------------------------------------------------------------
-- 1. CREATE STAGING TABLES
-- ---------------------------------------------------------------------

CREATE OR REPLACE TABLE STG_CUSTOMERS LIKE RETAIL_BANKING_DEMO.BRONZE.SRC_CUSTOMERS;
CREATE OR REPLACE TABLE STG_ACCOUNTS LIKE RETAIL_BANKING_DEMO.BRONZE.SRC_ACCOUNTS;
CREATE OR REPLACE TABLE STG_TRANSACTIONS LIKE RETAIL_BANKING_DEMO.BRONZE.SRC_TRANSACTIONS;
CREATE OR REPLACE TABLE STG_LOANS LIKE RETAIL_BANKING_DEMO.BRONZE.SRC_LOANS;

INSERT INTO STG_CUSTOMERS SELECT * FROM RETAIL_BANKING_DEMO.BRONZE.SRC_CUSTOMERS;
INSERT INTO STG_ACCOUNTS SELECT * FROM RETAIL_BANKING_DEMO.BRONZE.SRC_ACCOUNTS;
INSERT INTO STG_TRANSACTIONS SELECT * FROM RETAIL_BANKING_DEMO.BRONZE.SRC_TRANSACTIONS;
INSERT INTO STG_LOANS SELECT * FROM RETAIL_BANKING_DEMO.BRONZE.SRC_LOANS;

-- ---------------------------------------------------------------------
-- 2. CREATE DATA QUALITY REJECTS TABLE
-- ---------------------------------------------------------------------

CREATE OR REPLACE TABLE DATA_QUALITY_REJECTS (
    REJECT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REJECT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RULE_NAME STRING,
    REJECT_REASON STRING,
    SEVERITY STRING,
    SOURCE_TABLE STRING,
    SOURCE_RECORD_ID STRING,
    COLUMN_NAME STRING,
    RECEIVED_PAYLOAD VARIANT,
    SOURCE_SYSTEM STRING,
    SOURCE_FILE STRING,
    BATCH_ID STRING,
    COMMENTS STRING
);

SET BATCH_ID = 'BATCH_' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD');
SET SOURCE_SYSTEM = 'CORE_BANKING_SYSTEM_SEA';

-- ---------------------------------------------------------------------
-- 3. DATA QUALITY RULES - CUSTOMERS
-- ---------------------------------------------------------------------

-- Rule 1: Invalid email format
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID, 
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'CUST_EMAIL_FORMAT',
    'Invalid email format - must contain @ and domain',
    'MEDIUM',
    'BRONZE.SRC_CUSTOMERS',
    CUSTOMER_ID,
    'EMAIL',
    OBJECT_CONSTRUCT(
        'CUSTOMER_ID', CUSTOMER_ID,
        'FIRST_NAME', FIRST_NAME,
        'LAST_NAME', LAST_NAME,
        'EMAIL', EMAIL,
        'CITY', CITY,
        'COUNTRY', COUNTRY
    ),
    $SOURCE_SYSTEM,
    'CUSTOMERS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_CUSTOMERS
WHERE EMAIL IS NOT NULL 
  AND NOT REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$');

-- Rule 2: Missing mandatory email
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'CUST_EMAIL_NOT_NULL',
    'Email is mandatory for customer records',
    'HIGH',
    'BRONZE.SRC_CUSTOMERS',
    CUSTOMER_ID,
    'EMAIL',
    OBJECT_CONSTRUCT(
        'CUSTOMER_ID', CUSTOMER_ID,
        'FIRST_NAME', FIRST_NAME,
        'LAST_NAME', LAST_NAME,
        'CITY', CITY,
        'COUNTRY', COUNTRY
    ),
    $SOURCE_SYSTEM,
    'CUSTOMERS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_CUSTOMERS
WHERE EMAIL IS NULL;

-- Rule 3: Duplicate customer ID
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'CUST_PK_DUPLICATE',
    'Duplicate primary key - CUSTOMER_ID must be unique',
    'HIGH',
    'BRONZE.SRC_CUSTOMERS',
    CUSTOMER_ID,
    'CUSTOMER_ID',
    OBJECT_CONSTRUCT(
        'CUSTOMER_ID', CUSTOMER_ID,
        'FIRST_NAME', FIRST_NAME,
        'LAST_NAME', LAST_NAME,
        'EMAIL', EMAIL,
        'COUNTRY', COUNTRY
    ),
    $SOURCE_SYSTEM,
    'CUSTOMERS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_CUSTOMERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CREATED_TS) > 1;

-- Rule 4: Suspicious short name
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'CUST_NAME_MIN_LENGTH',
    'First name or last name too short - possible data entry error',
    'LOW',
    'BRONZE.SRC_CUSTOMERS',
    CUSTOMER_ID,
    'FIRST_NAME',
    OBJECT_CONSTRUCT(
        'CUSTOMER_ID', CUSTOMER_ID,
        'FIRST_NAME', FIRST_NAME,
        'LAST_NAME', LAST_NAME,
        'COUNTRY', COUNTRY
    ),
    $SOURCE_SYSTEM,
    'CUSTOMERS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_CUSTOMERS
WHERE LEN(FIRST_NAME) < 2 OR LEN(LAST_NAME) < 2;

-- Rule 5: Suspicious age (too young for banking)
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'CUST_AGE_MINIMUM',
    'Customer age below minimum banking age (must be 18+)',
    'HIGH',
    'BRONZE.SRC_CUSTOMERS',
    CUSTOMER_ID,
    'DATE_OF_BIRTH',
    OBJECT_CONSTRUCT(
        'CUSTOMER_ID', CUSTOMER_ID,
        'FIRST_NAME', FIRST_NAME,
        'LAST_NAME', LAST_NAME,
        'DATE_OF_BIRTH', DATE_OF_BIRTH,
        'AGE', DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()),
        'COUNTRY', COUNTRY
    ),
    $SOURCE_SYSTEM,
    'CUSTOMERS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_CUSTOMERS
WHERE DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 18;

-- Rule 6: Invalid credit score
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'CUST_CREDIT_SCORE_RANGE',
    'Credit score must be between 300 and 850',
    'MEDIUM',
    'BRONZE.SRC_CUSTOMERS',
    CUSTOMER_ID,
    'CREDIT_SCORE',
    OBJECT_CONSTRUCT(
        'CUSTOMER_ID', CUSTOMER_ID,
        'FIRST_NAME', FIRST_NAME,
        'LAST_NAME', LAST_NAME,
        'CREDIT_SCORE', CREDIT_SCORE,
        'COUNTRY', COUNTRY
    ),
    $SOURCE_SYSTEM,
    'CUSTOMERS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_CUSTOMERS
WHERE CREDIT_SCORE IS NOT NULL 
  AND (CREDIT_SCORE < 300 OR CREDIT_SCORE > 850);

-- ---------------------------------------------------------------------
-- 4. DATA QUALITY RULES - ACCOUNTS
-- ---------------------------------------------------------------------

-- Rule 7: Referential integrity - Unknown customer
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'ACC_CUSTOMER_FK',
    'Referential integrity violation - Customer ID does not exist',
    'HIGH',
    'BRONZE.SRC_ACCOUNTS',
    a.ACCOUNT_ID,
    'CUSTOMER_ID',
    OBJECT_CONSTRUCT(
        'ACCOUNT_ID', a.ACCOUNT_ID,
        'CUSTOMER_ID', a.CUSTOMER_ID,
        'ACCOUNT_TYPE', a.ACCOUNT_TYPE,
        'CURRENT_BALANCE_MYR', a.CURRENT_BALANCE_MYR,
        'BRANCH_ID', a.BRANCH_ID
    ),
    $SOURCE_SYSTEM,
    'ACCOUNTS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_ACCOUNTS a
LEFT JOIN STG_CUSTOMERS c ON a.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;

-- Rule 8: Negative balance in non-loan accounts
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'ACC_BALANCE_NEGATIVE',
    'Checking/Savings account has negative balance without overdraft protection',
    'MEDIUM',
    'BRONZE.SRC_ACCOUNTS',
    ACCOUNT_ID,
    'CURRENT_BALANCE_MYR',
    OBJECT_CONSTRUCT(
        'ACCOUNT_ID', ACCOUNT_ID,
        'CUSTOMER_ID', CUSTOMER_ID,
        'ACCOUNT_TYPE', ACCOUNT_TYPE,
        'CURRENT_BALANCE_MYR', CURRENT_BALANCE_MYR,
        'BRANCH_ID', BRANCH_ID
    ),
    $SOURCE_SYSTEM,
    'ACCOUNTS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_ACCOUNTS
WHERE ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS')
  AND CURRENT_BALANCE_MYR < 0;

-- ---------------------------------------------------------------------
-- 5. DATA QUALITY RULES - TRANSACTIONS
-- ---------------------------------------------------------------------

-- Rule 9: Invalid transaction date format
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'TXN_DATE_FORMAT',
    'Transaction date format invalid - cannot parse timestamp',
    'HIGH',
    'BRONZE.SRC_TRANSACTIONS',
    TRANSACTION_ID,
    'TRANSACTION_DATE',
    OBJECT_CONSTRUCT(
        'TRANSACTION_ID', TRANSACTION_ID,
        'ACCOUNT_ID', ACCOUNT_ID,
        'TRANSACTION_DATE', TRANSACTION_DATE,
        'AMOUNT_MYR', AMOUNT_MYR,
        'MERCHANT_NAME', MERCHANT_NAME
    ),
    $SOURCE_SYSTEM,
    'TRANSACTIONS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_TRANSACTIONS
WHERE TRY_TO_TIMESTAMP_NTZ(TRANSACTION_DATE) IS NULL;

-- Rule 10: Future dated transaction
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'TXN_DATE_FUTURE',
    'Transaction date is in the future - potential data entry error',
    'MEDIUM',
    'BRONZE.SRC_TRANSACTIONS',
    TRANSACTION_ID,
    'TRANSACTION_DATE',
    OBJECT_CONSTRUCT(
        'TRANSACTION_ID', TRANSACTION_ID,
        'ACCOUNT_ID', ACCOUNT_ID,
        'TRANSACTION_DATE', TRANSACTION_DATE,
        'AMOUNT_MYR', AMOUNT_MYR
    ),
    $SOURCE_SYSTEM,
    'TRANSACTIONS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_TRANSACTIONS
WHERE TRY_TO_TIMESTAMP_NTZ(TRANSACTION_DATE) > CURRENT_TIMESTAMP();

-- Rule 11: NULL or zero amount
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'TXN_AMOUNT_NOT_NULL',
    'Transaction amount cannot be NULL or zero',
    'HIGH',
    'BRONZE.SRC_TRANSACTIONS',
    TRANSACTION_ID,
    'AMOUNT_MYR',
    OBJECT_CONSTRUCT(
        'TRANSACTION_ID', TRANSACTION_ID,
        'ACCOUNT_ID', ACCOUNT_ID,
        'TRANSACTION_DATE', TRANSACTION_DATE,
        'AMOUNT_MYR', AMOUNT_MYR,
        'MERCHANT_NAME', MERCHANT_NAME
    ),
    $SOURCE_SYSTEM,
    'TRANSACTIONS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_TRANSACTIONS
WHERE AMOUNT_MYR IS NULL OR AMOUNT_MYR = 0;

-- Rule 12: Negative amount for deposits/purchases
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'TXN_AMOUNT_SIGN',
    'Amount has incorrect sign for transaction type',
    'MEDIUM',
    'BRONZE.SRC_TRANSACTIONS',
    TRANSACTION_ID,
    'AMOUNT_MYR',
    OBJECT_CONSTRUCT(
        'TRANSACTION_ID', TRANSACTION_ID,
        'ACCOUNT_ID', ACCOUNT_ID,
        'TRANSACTION_TYPE', TRANSACTION_TYPE,
        'AMOUNT_MYR', AMOUNT_MYR
    ),
    $SOURCE_SYSTEM,
    'TRANSACTIONS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_TRANSACTIONS
WHERE TRANSACTION_TYPE IN ('DEPOSIT', 'PURCHASE')
  AND AMOUNT_MYR < 0;

-- Rule 13: Suspicious large amount (> 1 million MYR)
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'TXN_AMOUNT_THRESHOLD',
    'Transaction amount exceeds suspicious threshold - requires review',
    'HIGH',
    'BRONZE.SRC_TRANSACTIONS',
    TRANSACTION_ID,
    'AMOUNT_MYR',
    OBJECT_CONSTRUCT(
        'TRANSACTION_ID', TRANSACTION_ID,
        'ACCOUNT_ID', ACCOUNT_ID,
        'TRANSACTION_TYPE', TRANSACTION_TYPE,
        'AMOUNT_MYR', AMOUNT_MYR,
        'MERCHANT_NAME', MERCHANT_NAME
    ),
    $SOURCE_SYSTEM,
    'TRANSACTIONS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_TRANSACTIONS
WHERE AMOUNT_MYR > 1000000;

-- Rule 14: Unknown account reference
INSERT INTO DATA_QUALITY_REJECTS (
    RULE_NAME, REJECT_REASON, SEVERITY, SOURCE_TABLE, SOURCE_RECORD_ID,
    COLUMN_NAME, RECEIVED_PAYLOAD, SOURCE_SYSTEM, SOURCE_FILE, BATCH_ID
)
SELECT
    'TXN_ACCOUNT_FK',
    'Referential integrity violation - Account ID does not exist',
    'HIGH',
    'BRONZE.SRC_TRANSACTIONS',
    t.TRANSACTION_ID,
    'ACCOUNT_ID',
    OBJECT_CONSTRUCT(
        'TRANSACTION_ID', t.TRANSACTION_ID,
        'ACCOUNT_ID', t.ACCOUNT_ID,
        'CUSTOMER_ID', t.CUSTOMER_ID,
        'AMOUNT_MYR', t.AMOUNT_MYR
    ),
    $SOURCE_SYSTEM,
    'TRANSACTIONS_SEA_' || $BATCH_ID || '.csv',
    $BATCH_ID
FROM STG_TRANSACTIONS t
LEFT JOIN STG_ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
WHERE a.ACCOUNT_ID IS NULL;

-- =====================================================================
-- GOLD LAYER - CURATED DATA
-- =====================================================================

USE SCHEMA GOLD;

-- ---------------------------------------------------------------------
-- 1. CURATED CUSTOMERS
-- ---------------------------------------------------------------------

CREATE OR REPLACE TABLE CUSTOMERS AS
SELECT *
FROM RETAIL_BANKING_DEMO.SILVER.STG_CUSTOMERS c
WHERE c.CUSTOMER_ID NOT IN (
    SELECT DISTINCT SOURCE_RECORD_ID
    FROM RETAIL_BANKING_DEMO.SILVER.DATA_QUALITY_REJECTS
    WHERE SOURCE_TABLE = 'BRONZE.SRC_CUSTOMERS'
);

-- Add primary key
ALTER TABLE CUSTOMERS ADD PRIMARY KEY (CUSTOMER_ID);

-- ---------------------------------------------------------------------
-- 2. CURATED ACCOUNTS
-- ---------------------------------------------------------------------

CREATE OR REPLACE TABLE ACCOUNTS AS
SELECT *
FROM RETAIL_BANKING_DEMO.SILVER.STG_ACCOUNTS a
WHERE a.ACCOUNT_ID NOT IN (
    SELECT DISTINCT SOURCE_RECORD_ID
    FROM RETAIL_BANKING_DEMO.SILVER.DATA_QUALITY_REJECTS
    WHERE SOURCE_TABLE = 'BRONZE.SRC_ACCOUNTS'
);

-- Add primary key
ALTER TABLE ACCOUNTS ADD PRIMARY KEY (ACCOUNT_ID);

-- ---------------------------------------------------------------------
-- 3. CURATED TRANSACTIONS
-- ---------------------------------------------------------------------

CREATE OR REPLACE TABLE TRANSACTIONS AS
SELECT
    t.TRANSACTION_ID,
    t.ACCOUNT_ID,
    t.CUSTOMER_ID,
    TRY_TO_TIMESTAMP_NTZ(t.TRANSACTION_DATE) AS TRANSACTION_DATE,
    t.TRANSACTION_TYPE,
    ABS(t.AMOUNT_MYR) AS AMOUNT_MYR,
    t.CHANNEL,
    t.MERCHANT_NAME,
    t.CATEGORY,
    t.DESCRIPTION,
    t.STATUS,
    t.CREATED_TS
FROM RETAIL_BANKING_DEMO.SILVER.STG_TRANSACTIONS t
WHERE t.TRANSACTION_ID NOT IN (
    SELECT DISTINCT SOURCE_RECORD_ID
    FROM RETAIL_BANKING_DEMO.SILVER.DATA_QUALITY_REJECTS
    WHERE SOURCE_TABLE = 'BRONZE.SRC_TRANSACTIONS'
);

-- Add primary key
ALTER TABLE TRANSACTIONS ADD PRIMARY KEY (TRANSACTION_ID);

-- ---------------------------------------------------------------------
-- 4. CURATED LOANS
-- ---------------------------------------------------------------------

CREATE OR REPLACE TABLE LOANS AS
SELECT *
FROM RETAIL_BANKING_DEMO.SILVER.STG_LOANS;

-- Add primary key
ALTER TABLE LOANS ADD PRIMARY KEY (LOAN_ID);

-- =====================================================================
-- ANALYTICS LAYER - BUSINESS VIEWS
-- =====================================================================

USE SCHEMA ANALYTICS;

-- Customer 360 View
CREATE OR REPLACE VIEW VW_CUSTOMER_360 AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS FULL_NAME,
    c.EMAIL,
    c.PHONE,
    c.CITY,
    c.STATE,
    c.COUNTRY,
    c.CUSTOMER_SEGMENT,
    c.CREDIT_SCORE,
    c.ANNUAL_INCOME_MYR,
    c.CUSTOMER_SINCE,
    DATEDIFF('YEAR', c.CUSTOMER_SINCE, CURRENT_DATE()) AS YEARS_AS_CUSTOMER,
    
    COUNT(DISTINCT a.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
    SUM(CASE WHEN a.ACCOUNT_TYPE = 'CHECKING' THEN 1 ELSE 0 END) AS CHECKING_ACCOUNTS,
    SUM(CASE WHEN a.ACCOUNT_TYPE = 'SAVINGS' THEN 1 ELSE 0 END) AS SAVINGS_ACCOUNTS,
    SUM(CASE WHEN a.ACCOUNT_TYPE = 'CREDIT_CARD' THEN 1 ELSE 0 END) AS CREDIT_CARDS,
    SUM(a.CURRENT_BALANCE_MYR) AS TOTAL_BALANCE_MYR,
    
    COUNT(DISTINCT CASE WHEN t.TRANSACTION_DATE >= DATEADD('DAY', -30, CURRENT_DATE()) THEN t.TRANSACTION_ID END) AS TRANSACTIONS_30D,
    SUM(CASE WHEN t.TRANSACTION_DATE >= DATEADD('DAY', -30, CURRENT_DATE()) THEN t.AMOUNT_MYR ELSE 0 END) AS TRANSACTION_VOLUME_30D_MYR,
    
    COUNT(DISTINCT l.LOAN_ID) AS TOTAL_LOANS,
    SUM(l.OUTSTANDING_BALANCE_MYR) AS TOTAL_LOAN_BALANCE_MYR

FROM RETAIL_BANKING_DEMO.GOLD.CUSTOMERS c
LEFT JOIN RETAIL_BANKING_DEMO.GOLD.ACCOUNTS a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN RETAIL_BANKING_DEMO.GOLD.TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN RETAIL_BANKING_DEMO.GOLD.LOANS l ON c.CUSTOMER_ID = l.CUSTOMER_ID
GROUP BY 
    c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.PHONE, c.CITY, c.STATE, c.COUNTRY,
    c.CUSTOMER_SEGMENT, c.CREDIT_SCORE, c.ANNUAL_INCOME_MYR, c.CUSTOMER_SINCE;

-- Transaction Summary View
CREATE OR REPLACE VIEW VW_TRANSACTION_SUMMARY AS
SELECT
    DATE(t.TRANSACTION_DATE) AS TRANSACTION_DATE,
    t.TRANSACTION_TYPE,
    t.CHANNEL,
    t.CATEGORY,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(t.AMOUNT_MYR) AS TOTAL_AMOUNT_MYR,
    AVG(t.AMOUNT_MYR) AS AVG_AMOUNT_MYR,
    MIN(t.AMOUNT_MYR) AS MIN_AMOUNT_MYR,
    MAX(t.AMOUNT_MYR) AS MAX_AMOUNT_MYR
FROM RETAIL_BANKING_DEMO.GOLD.TRANSACTIONS t
GROUP BY DATE(t.TRANSACTION_DATE), t.TRANSACTION_TYPE, t.CHANNEL, t.CATEGORY;

-- Loan Portfolio View
CREATE OR REPLACE VIEW VW_LOAN_PORTFOLIO AS
SELECT
    l.LOAN_TYPE,
    l.LOAN_STATUS,
    COUNT(*) AS LOAN_COUNT,
    SUM(l.LOAN_AMOUNT_MYR) AS TOTAL_LOAN_AMOUNT_MYR,
    SUM(l.OUTSTANDING_BALANCE_MYR) AS TOTAL_OUTSTANDING_MYR,
    AVG(l.INTEREST_RATE) AS AVG_INTEREST_RATE,
    AVG(l.CREDIT_SCORE_AT_ORIGINATION) AS AVG_CREDIT_SCORE
FROM RETAIL_BANKING_DEMO.GOLD.LOANS l
GROUP BY l.LOAN_TYPE, l.LOAN_STATUS;

-- =====================================================================
-- SUMMARY & VERIFICATION
-- =====================================================================

-- Count rejects by rule
SELECT
    RULE_NAME,
    SEVERITY,
    COUNT(*) AS REJECT_COUNT
FROM RETAIL_BANKING_DEMO.SILVER.DATA_QUALITY_REJECTS
GROUP BY RULE_NAME, SEVERITY
ORDER BY REJECT_COUNT DESC;

-- Summary counts
SELECT 'SOURCE_CUSTOMERS' AS LAYER, COUNT(*) AS ROW_COUNT FROM RETAIL_BANKING_DEMO.BRONZE.SRC_CUSTOMERS
UNION ALL SELECT 'CURATED_CUSTOMERS', COUNT(*) FROM RETAIL_BANKING_DEMO.GOLD.CUSTOMERS
UNION ALL SELECT 'REJECTED_CUSTOMERS', COUNT(DISTINCT SOURCE_RECORD_ID) FROM RETAIL_BANKING_DEMO.SILVER.DATA_QUALITY_REJECTS WHERE SOURCE_TABLE = 'BRONZE.SRC_CUSTOMERS'
UNION ALL SELECT 'SOURCE_TRANSACTIONS', COUNT(*) FROM RETAIL_BANKING_DEMO.BRONZE.SRC_TRANSACTIONS
UNION ALL SELECT 'CURATED_TRANSACTIONS', COUNT(*) FROM RETAIL_BANKING_DEMO.GOLD.TRANSACTIONS
UNION ALL SELECT 'REJECTED_TRANSACTIONS', COUNT(DISTINCT SOURCE_RECORD_ID) FROM RETAIL_BANKING_DEMO.SILVER.DATA_QUALITY_REJECTS WHERE SOURCE_TABLE = 'BRONZE.SRC_TRANSACTIONS';

SELECT '✓ DATA QUALITY VALIDATION COMPLETE - SEA REGION!' AS STATUS;